#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = %cd%

CC = gcc.exe
CXX = g++.exe
AR = ar.exe
LD = g++.exe
WINDRES = windres.exe

INC = -ISDL2_Mingw32\\include
CFLAGS = 
RESINC = 
LIBDIR = -LSDL2_Mingw32\\lib
LIB = 
LDFLAGS = -lmingw32 -lSDL2main -lSDL2 -lSDL2_image -lSDL2_ttf

INC_MICROENGINE_TEST = $(INC)
CFLAGS_MICROENGINE_TEST = $(CFLAGS)
RESINC_MICROENGINE_TEST = $(RESINC)
RCFLAGS_MICROENGINE_TEST = $(RCFLAGS)
LIBDIR_MICROENGINE_TEST = $(LIBDIR)
LIB_MICROENGINE_TEST = $(LIB) 
LDFLAGS_MICROENGINE_TEST = $(LDFLAGS)
OBJDIR_MICROENGINE_TEST = .objs
DEP_MICROENGINE_TEST = 
OUT_MICROENGINE_TEST = bin\\MicroEngine_test.exe

INC_PONG_GAME = $(INC)
CFLAGS_PONG_GAME = $(CFLAGS)
RESINC_PONG_GAME = $(RESINC)
RCFLAGS_PONG_GAME = $(RCFLAGS)
LIBDIR_PONG_GAME = $(LIBDIR)
LIB_PONG_GAME = $(LIB) 
LDFLAGS_PONG_GAME = $(LDFLAGS)
OBJDIR_PONG_GAME = .objs
DEP_PONG_GAME = 
OUT_PONG_GAME = bin\\Pong_game.exe

INC_MICROUI_TEST = $(INC)
CFLAGS_MICROUI_TEST = $(CFLAGS)
RESINC_MICROUI_TEST = $(RESINC)
RCFLAGS_MICROUI_TEST = $(RCFLAGS)
LIBDIR_MICROUI_TEST = $(LIBDIR)
LIB_MICROUI_TEST = $(LIB) 
LDFLAGS_MICROUI_TEST = $(LDFLAGS)
OBJDIR_MICROUI_TEST = .objs
DEP_MICROUI_TEST = 
OUT_MICROUI_TEST = bin\\MicroUI_test.exe

INC_SPACESHIP_GAME = $(INC)
CFLAGS_SPACESHIP_GAME = $(CFLAGS)
RESINC_SPACESHIP_GAME = $(RESINC)
RCFLAGS_SPACESHIP_GAME = $(RCFLAGS)
LIBDIR_SPACESHIP_GAME = $(LIBDIR)
LIB_SPACESHIP_GAME = $(LIB) 
LDFLAGS_SPACESHIP_GAME = $(LDFLAGS)
OBJDIR_SPACESHIP_GAME = .objs
DEP_SPACESHIP_GAME = 
OUT_SPACESHIP_GAME = bin\\SpaceShip_game.exe

INC_FLAPPYBIRD_CLONE_GAME = $(INC)
CFLAGS_FLAPPYBIRD_CLONE_GAME = $(CFLAGS)
RESINC_FLAPPYBIRD_CLONE_GAME = $(RESINC)
RCFLAGS_FLAPPYBIRD_CLONE_GAME = $(RCFLAGS)
LIBDIR_FLAPPYBIRD_CLONE_GAME = $(LIBDIR)
LIB_FLAPPYBIRD_CLONE_GAME = $(LIB) 
LDFLAGS_FLAPPYBIRD_CLONE_GAME = $(LDFLAGS)
OBJDIR_FLAPPYBIRD_CLONE_GAME = .objs
DEP_FLAPPYBIRD_CLONE_GAME = 
OUT_FLAPPYBIRD_CLONE_GAME = bin\\FlappyBird_clone.exe

OBJ_MICROENGINE_TEST = $(OBJDIR_MICROENGINE_TEST)\\src\\MicroUI\\MUI_Button.o $(OBJDIR_MICROENGINE_TEST)\\src\\MicroEngine\\ME_GameObject.o $(OBJDIR_MICROENGINE_TEST)\\src\\MicroEngine\\ME_ParticleSystem.o $(OBJDIR_MICROENGINE_TEST)\\src\\MicroEngine\\ME_Renderer.o $(OBJDIR_MICROENGINE_TEST)\\src\\MicroEngine\\ME_Utility.o $(OBJDIR_MICROENGINE_TEST)\\src\\MicroEngine\\ME_Vector2D.o $(OBJDIR_MICROENGINE_TEST)\\src\\MicroEngine\\MicroEngine.o $(OBJDIR_MICROENGINE_TEST)\\src\\MicroEngine_Test.o $(OBJDIR_MICROENGINE_TEST)\\src\\MicroPhysics\\MicroPhysics.o $(OBJDIR_MICROENGINE_TEST)\\src\\MicroEngine\\ME_Camer2D.o $(OBJDIR_MICROENGINE_TEST)\\src\\MicroUI\\MUI_CheckBox.o $(OBJDIR_MICROENGINE_TEST)\\src\\MicroUI\\MUI_Slider.o $(OBJDIR_MICROENGINE_TEST)\\src\\MicroUI\\MUI_TextBox.o $(OBJDIR_MICROENGINE_TEST)\\src\\MicroUI\\MicroUI.o $(OBJDIR_MICROENGINE_TEST)\\src\\MicroEngine\\ME_AssetHandler.o

OBJ_PONG_GAME = $(OBJDIR_PONG_GAME)\\src\\MicroUI\\MUI_Button.o $(OBJDIR_PONG_GAME)\\src\\MicroEngine\\ME_GameObject.o $(OBJDIR_PONG_GAME)\\src\\MicroEngine\\ME_ParticleSystem.o $(OBJDIR_PONG_GAME)\\src\\MicroEngine\\ME_Renderer.o $(OBJDIR_PONG_GAME)\\src\\MicroEngine\\ME_Utility.o $(OBJDIR_PONG_GAME)\\src\\MicroEngine\\ME_Vector2D.o $(OBJDIR_PONG_GAME)\\src\\MicroEngine\\MicroEngine.o $(OBJDIR_PONG_GAME)\\src\\MicroPhysics\\MicroPhysics.o $(OBJDIR_PONG_GAME)\\src\\MicroEngine\\ME_Camer2D.o $(OBJDIR_PONG_GAME)\\src\\MicroUI\\MUI_CheckBox.o $(OBJDIR_PONG_GAME)\\src\\MicroUI\\MUI_Slider.o $(OBJDIR_PONG_GAME)\\src\\MicroUI\\MUI_TextBox.o $(OBJDIR_PONG_GAME)\\src\\MicroUI\\MicroUI.o $(OBJDIR_PONG_GAME)\\src\\Pong.o $(OBJDIR_PONG_GAME)\\src\\MicroEngine\\ME_AssetHandler.o

OBJ_MICROUI_TEST = $(OBJDIR_MICROUI_TEST)\\src\\MicroUI\\MUI_Button.o $(OBJDIR_MICROUI_TEST)\\src\\MicroEngine\\ME_GameObject.o $(OBJDIR_MICROUI_TEST)\\src\\MicroEngine\\ME_ParticleSystem.o $(OBJDIR_MICROUI_TEST)\\src\\MicroEngine\\ME_Renderer.o $(OBJDIR_MICROUI_TEST)\\src\\MicroEngine\\ME_Utility.o $(OBJDIR_MICROUI_TEST)\\src\\MicroEngine\\ME_Vector2D.o $(OBJDIR_MICROUI_TEST)\\src\\MicroEngine\\MicroEngine.o $(OBJDIR_MICROUI_TEST)\\src\\MicroPhysics\\MicroPhysics.o $(OBJDIR_MICROUI_TEST)\\src\\MicroEngine\\ME_Camer2D.o $(OBJDIR_MICROUI_TEST)\\src\\MicroUI\\MUI_CheckBox.o $(OBJDIR_MICROUI_TEST)\\src\\MicroUI\\MUI_Slider.o $(OBJDIR_MICROUI_TEST)\\src\\MicroUI\\MUI_TextBox.o $(OBJDIR_MICROUI_TEST)\\src\\MicroUI\\MicroUI.o $(OBJDIR_MICROUI_TEST)\\src\\MicroUI_Test.o $(OBJDIR_MICROUI_TEST)\\src\\MicroEngine\\ME_AssetHandler.o

OBJ_SPACESHIP_GAME = $(OBJDIR_SPACESHIP_GAME)\\src\\MicroUI\\MUI_Button.o $(OBJDIR_SPACESHIP_GAME)\\src\\MicroEngine\\ME_GameObject.o $(OBJDIR_SPACESHIP_GAME)\\src\\MicroEngine\\ME_ParticleSystem.o $(OBJDIR_SPACESHIP_GAME)\\src\\MicroEngine\\ME_Renderer.o $(OBJDIR_SPACESHIP_GAME)\\src\\MicroEngine\\ME_Utility.o $(OBJDIR_SPACESHIP_GAME)\\src\\MicroEngine\\ME_Vector2D.o $(OBJDIR_SPACESHIP_GAME)\\src\\MicroEngine\\MicroEngine.o $(OBJDIR_SPACESHIP_GAME)\\src\\MicroPhysics\\MicroPhysics.o $(OBJDIR_SPACESHIP_GAME)\\src\\MicroEngine\\ME_Camer2D.o $(OBJDIR_SPACESHIP_GAME)\\src\\MicroUI\\MUI_CheckBox.o $(OBJDIR_SPACESHIP_GAME)\\src\\MicroUI\\MUI_Slider.o $(OBJDIR_SPACESHIP_GAME)\\src\\MicroUI\\MUI_TextBox.o $(OBJDIR_SPACESHIP_GAME)\\src\\MicroUI\\MicroUI.o $(OBJDIR_SPACESHIP_GAME)\\src\\SpaceShip_Game.o $(OBJDIR_SPACESHIP_GAME)\\src\\MicroEngine\\ME_AssetHandler.o

OBJ_FLAPPYBIRD_CLONE_GAME = $(OBJDIR_FLAPPYBIRD_CLONE_GAME)\\src\\MicroUI\\MUI_Button.o $(OBJDIR_FLAPPYBIRD_CLONE_GAME)\\src\\MicroEngine\\ME_GameObject.o $(OBJDIR_FLAPPYBIRD_CLONE_GAME)\\src\\MicroEngine\\ME_ParticleSystem.o $(OBJDIR_FLAPPYBIRD_CLONE_GAME)\\src\\MicroEngine\\ME_Renderer.o $(OBJDIR_FLAPPYBIRD_CLONE_GAME)\\src\\MicroEngine\\ME_Utility.o $(OBJDIR_FLAPPYBIRD_CLONE_GAME)\\src\\MicroEngine\\ME_Vector2D.o $(OBJDIR_FLAPPYBIRD_CLONE_GAME)\\src\\MicroEngine\\MicroEngine.o $(OBJDIR_FLAPPYBIRD_CLONE_GAME)\\src\\MicroPhysics\\MicroPhysics.o $(OBJDIR_FLAPPYBIRD_CLONE_GAME)\\src\\MicroEngine\\ME_Camer2D.o $(OBJDIR_FLAPPYBIRD_CLONE_GAME)\\src\\MicroUI\\MUI_CheckBox.o $(OBJDIR_FLAPPYBIRD_CLONE_GAME)\\src\\MicroUI\\MUI_Slider.o $(OBJDIR_FLAPPYBIRD_CLONE_GAME)\\src\\MicroUI\\MUI_TextBox.o $(OBJDIR_FLAPPYBIRD_CLONE_GAME)\\src\\MicroUI\\MicroUI.o $(OBJDIR_FLAPPYBIRD_CLONE_GAME)\\src\\FlappyBird_game.o $(OBJDIR_FLAPPYBIRD_CLONE_GAME)\\src\\MicroEngine\\ME_AssetHandler.o

all: microengine_test pong_game microui_test spaceship_game flappybird_clone_game

clean: clean_microengine_test clean_pong_game clean_microui_test clean_spaceship_game clean_flappybird_clone_game

before_microengine_test: 
	cmd /c if not exist bin md bin
	cmd /c if not exist $(OBJDIR_MICROENGINE_TEST)\\src\\MicroUI md $(OBJDIR_MICROENGINE_TEST)\\src\\MicroUI
	cmd /c if not exist $(OBJDIR_MICROENGINE_TEST)\\src\\MicroEngine md $(OBJDIR_MICROENGINE_TEST)\\src\\MicroEngine
	cmd /c if not exist $(OBJDIR_MICROENGINE_TEST)\\src md $(OBJDIR_MICROENGINE_TEST)\\src
	cmd /c if not exist $(OBJDIR_MICROENGINE_TEST)\\src\\MicroPhysics md $(OBJDIR_MICROENGINE_TEST)\\src\\MicroPhysics

after_microengine_test: 

microengine_test: before_microengine_test out_microengine_test after_microengine_test

out_microengine_test: before_microengine_test $(OBJ_MICROENGINE_TEST) $(DEP_MICROENGINE_TEST)
	$(LD) $(LIBDIR_MICROENGINE_TEST) -o $(OUT_MICROENGINE_TEST) $(OBJ_MICROENGINE_TEST)  $(LDFLAGS_MICROENGINE_TEST) $(LIB_MICROENGINE_TEST)

$(OBJDIR_MICROENGINE_TEST)\\src\\MicroUI\\MUI_Button.o: src\\MicroUI\\MUI_Button.c
	$(CC) $(CFLAGS_MICROENGINE_TEST) $(INC_MICROENGINE_TEST) -c src\\MicroUI\\MUI_Button.c -o $(OBJDIR_MICROENGINE_TEST)\\src\\MicroUI\\MUI_Button.o

$(OBJDIR_MICROENGINE_TEST)\\src\\MicroEngine\\ME_GameObject.o: src\\MicroEngine\\ME_GameObject.c
	$(CC) $(CFLAGS_MICROENGINE_TEST) $(INC_MICROENGINE_TEST) -c src\\MicroEngine\\ME_GameObject.c -o $(OBJDIR_MICROENGINE_TEST)\\src\\MicroEngine\\ME_GameObject.o

$(OBJDIR_MICROENGINE_TEST)\\src\\MicroEngine\\ME_ParticleSystem.o: src\\MicroEngine\\ME_ParticleSystem.c
	$(CC) $(CFLAGS_MICROENGINE_TEST) $(INC_MICROENGINE_TEST) -c src\\MicroEngine\\ME_ParticleSystem.c -o $(OBJDIR_MICROENGINE_TEST)\\src\\MicroEngine\\ME_ParticleSystem.o

$(OBJDIR_MICROENGINE_TEST)\\src\\MicroEngine\\ME_Renderer.o: src\\MicroEngine\\ME_Renderer.c
	$(CC) $(CFLAGS_MICROENGINE_TEST) $(INC_MICROENGINE_TEST) -c src\\MicroEngine\\ME_Renderer.c -o $(OBJDIR_MICROENGINE_TEST)\\src\\MicroEngine\\ME_Renderer.o

$(OBJDIR_MICROENGINE_TEST)\\src\\MicroEngine\\ME_Utility.o: src\\MicroEngine\\ME_Utility.c
	$(CC) $(CFLAGS_MICROENGINE_TEST) $(INC_MICROENGINE_TEST) -c src\\MicroEngine\\ME_Utility.c -o $(OBJDIR_MICROENGINE_TEST)\\src\\MicroEngine\\ME_Utility.o

$(OBJDIR_MICROENGINE_TEST)\\src\\MicroEngine\\ME_Vector2D.o: src\\MicroEngine\\ME_Vector2D.c
	$(CC) $(CFLAGS_MICROENGINE_TEST) $(INC_MICROENGINE_TEST) -c src\\MicroEngine\\ME_Vector2D.c -o $(OBJDIR_MICROENGINE_TEST)\\src\\MicroEngine\\ME_Vector2D.o

$(OBJDIR_MICROENGINE_TEST)\\src\\MicroEngine\\MicroEngine.o: src\\MicroEngine\\MicroEngine.c
	$(CC) $(CFLAGS_MICROENGINE_TEST) $(INC_MICROENGINE_TEST) -c src\\MicroEngine\\MicroEngine.c -o $(OBJDIR_MICROENGINE_TEST)\\src\\MicroEngine\\MicroEngine.o

$(OBJDIR_MICROENGINE_TEST)\\src\\MicroEngine_Test.o: src\\MicroEngine_Test.c
	$(CC) $(CFLAGS_MICROENGINE_TEST) $(INC_MICROENGINE_TEST) -c src\\MicroEngine_Test.c -o $(OBJDIR_MICROENGINE_TEST)\\src\\MicroEngine_Test.o

$(OBJDIR_MICROENGINE_TEST)\\src\\MicroPhysics\\MicroPhysics.o: src\\MicroPhysics\\MicroPhysics.c
	$(CC) $(CFLAGS_MICROENGINE_TEST) $(INC_MICROENGINE_TEST) -c src\\MicroPhysics\\MicroPhysics.c -o $(OBJDIR_MICROENGINE_TEST)\\src\\MicroPhysics\\MicroPhysics.o

$(OBJDIR_MICROENGINE_TEST)\\src\\MicroEngine\\ME_Camer2D.o: src\\MicroEngine\\ME_Camer2D.c
	$(CC) $(CFLAGS_MICROENGINE_TEST) $(INC_MICROENGINE_TEST) -c src\\MicroEngine\\ME_Camer2D.c -o $(OBJDIR_MICROENGINE_TEST)\\src\\MicroEngine\\ME_Camer2D.o

$(OBJDIR_MICROENGINE_TEST)\\src\\MicroUI\\MUI_CheckBox.o: src\\MicroUI\\MUI_CheckBox.c
	$(CC) $(CFLAGS_MICROENGINE_TEST) $(INC_MICROENGINE_TEST) -c src\\MicroUI\\MUI_CheckBox.c -o $(OBJDIR_MICROENGINE_TEST)\\src\\MicroUI\\MUI_CheckBox.o

$(OBJDIR_MICROENGINE_TEST)\\src\\MicroUI\\MUI_Slider.o: src\\MicroUI\\MUI_Slider.c
	$(CC) $(CFLAGS_MICROENGINE_TEST) $(INC_MICROENGINE_TEST) -c src\\MicroUI\\MUI_Slider.c -o $(OBJDIR_MICROENGINE_TEST)\\src\\MicroUI\\MUI_Slider.o

$(OBJDIR_MICROENGINE_TEST)\\src\\MicroUI\\MUI_TextBox.o: src\\MicroUI\\MUI_TextBox.c
	$(CC) $(CFLAGS_MICROENGINE_TEST) $(INC_MICROENGINE_TEST) -c src\\MicroUI\\MUI_TextBox.c -o $(OBJDIR_MICROENGINE_TEST)\\src\\MicroUI\\MUI_TextBox.o

$(OBJDIR_MICROENGINE_TEST)\\src\\MicroUI\\MicroUI.o: src\\MicroUI\\MicroUI.c
	$(CC) $(CFLAGS_MICROENGINE_TEST) $(INC_MICROENGINE_TEST) -c src\\MicroUI\\MicroUI.c -o $(OBJDIR_MICROENGINE_TEST)\\src\\MicroUI\\MicroUI.o

$(OBJDIR_MICROENGINE_TEST)\\src\\MicroEngine\\ME_AssetHandler.o: src\\MicroEngine\\ME_AssetHandler.c
	$(CC) $(CFLAGS_MICROENGINE_TEST) $(INC_MICROENGINE_TEST) -c src\\MicroEngine\\ME_AssetHandler.c -o $(OBJDIR_MICROENGINE_TEST)\\src\\MicroEngine\\ME_AssetHandler.o

clean_microengine_test: 
	cmd /c del /f $(OBJ_MICROENGINE_TEST) $(OUT_MICROENGINE_TEST)
	cmd /c rd bin
	cmd /c rd $(OBJDIR_MICROENGINE_TEST)\\src\\MicroUI
	cmd /c rd $(OBJDIR_MICROENGINE_TEST)\\src\\MicroEngine
	cmd /c rd $(OBJDIR_MICROENGINE_TEST)\\src
	cmd /c rd $(OBJDIR_MICROENGINE_TEST)\\src\\MicroPhysics

before_pong_game: 
	cmd /c if not exist bin md bin
	cmd /c if not exist $(OBJDIR_PONG_GAME)\\src\\MicroUI md $(OBJDIR_PONG_GAME)\\src\\MicroUI
	cmd /c if not exist $(OBJDIR_PONG_GAME)\\src\\MicroEngine md $(OBJDIR_PONG_GAME)\\src\\MicroEngine
	cmd /c if not exist $(OBJDIR_PONG_GAME)\\src\\MicroPhysics md $(OBJDIR_PONG_GAME)\\src\\MicroPhysics
	cmd /c if not exist $(OBJDIR_PONG_GAME)\\src md $(OBJDIR_PONG_GAME)\\src

after_pong_game: 

pong_game: before_pong_game out_pong_game after_pong_game

out_pong_game: before_pong_game $(OBJ_PONG_GAME) $(DEP_PONG_GAME)
	$(LD) $(LIBDIR_PONG_GAME) -o $(OUT_PONG_GAME) $(OBJ_PONG_GAME)  $(LDFLAGS_PONG_GAME) $(LIB_PONG_GAME)

$(OBJDIR_PONG_GAME)\\src\\MicroUI\\MUI_Button.o: src\\MicroUI\\MUI_Button.c
	$(CC) $(CFLAGS_PONG_GAME) $(INC_PONG_GAME) -c src\\MicroUI\\MUI_Button.c -o $(OBJDIR_PONG_GAME)\\src\\MicroUI\\MUI_Button.o

$(OBJDIR_PONG_GAME)\\src\\MicroEngine\\ME_GameObject.o: src\\MicroEngine\\ME_GameObject.c
	$(CC) $(CFLAGS_PONG_GAME) $(INC_PONG_GAME) -c src\\MicroEngine\\ME_GameObject.c -o $(OBJDIR_PONG_GAME)\\src\\MicroEngine\\ME_GameObject.o

$(OBJDIR_PONG_GAME)\\src\\MicroEngine\\ME_ParticleSystem.o: src\\MicroEngine\\ME_ParticleSystem.c
	$(CC) $(CFLAGS_PONG_GAME) $(INC_PONG_GAME) -c src\\MicroEngine\\ME_ParticleSystem.c -o $(OBJDIR_PONG_GAME)\\src\\MicroEngine\\ME_ParticleSystem.o

$(OBJDIR_PONG_GAME)\\src\\MicroEngine\\ME_Renderer.o: src\\MicroEngine\\ME_Renderer.c
	$(CC) $(CFLAGS_PONG_GAME) $(INC_PONG_GAME) -c src\\MicroEngine\\ME_Renderer.c -o $(OBJDIR_PONG_GAME)\\src\\MicroEngine\\ME_Renderer.o

$(OBJDIR_PONG_GAME)\\src\\MicroEngine\\ME_Utility.o: src\\MicroEngine\\ME_Utility.c
	$(CC) $(CFLAGS_PONG_GAME) $(INC_PONG_GAME) -c src\\MicroEngine\\ME_Utility.c -o $(OBJDIR_PONG_GAME)\\src\\MicroEngine\\ME_Utility.o

$(OBJDIR_PONG_GAME)\\src\\MicroEngine\\ME_Vector2D.o: src\\MicroEngine\\ME_Vector2D.c
	$(CC) $(CFLAGS_PONG_GAME) $(INC_PONG_GAME) -c src\\MicroEngine\\ME_Vector2D.c -o $(OBJDIR_PONG_GAME)\\src\\MicroEngine\\ME_Vector2D.o

$(OBJDIR_PONG_GAME)\\src\\MicroEngine\\MicroEngine.o: src\\MicroEngine\\MicroEngine.c
	$(CC) $(CFLAGS_PONG_GAME) $(INC_PONG_GAME) -c src\\MicroEngine\\MicroEngine.c -o $(OBJDIR_PONG_GAME)\\src\\MicroEngine\\MicroEngine.o

$(OBJDIR_PONG_GAME)\\src\\MicroPhysics\\MicroPhysics.o: src\\MicroPhysics\\MicroPhysics.c
	$(CC) $(CFLAGS_PONG_GAME) $(INC_PONG_GAME) -c src\\MicroPhysics\\MicroPhysics.c -o $(OBJDIR_PONG_GAME)\\src\\MicroPhysics\\MicroPhysics.o

$(OBJDIR_PONG_GAME)\\src\\MicroEngine\\ME_Camer2D.o: src\\MicroEngine\\ME_Camer2D.c
	$(CC) $(CFLAGS_PONG_GAME) $(INC_PONG_GAME) -c src\\MicroEngine\\ME_Camer2D.c -o $(OBJDIR_PONG_GAME)\\src\\MicroEngine\\ME_Camer2D.o

$(OBJDIR_PONG_GAME)\\src\\MicroUI\\MUI_CheckBox.o: src\\MicroUI\\MUI_CheckBox.c
	$(CC) $(CFLAGS_PONG_GAME) $(INC_PONG_GAME) -c src\\MicroUI\\MUI_CheckBox.c -o $(OBJDIR_PONG_GAME)\\src\\MicroUI\\MUI_CheckBox.o

$(OBJDIR_PONG_GAME)\\src\\MicroUI\\MUI_Slider.o: src\\MicroUI\\MUI_Slider.c
	$(CC) $(CFLAGS_PONG_GAME) $(INC_PONG_GAME) -c src\\MicroUI\\MUI_Slider.c -o $(OBJDIR_PONG_GAME)\\src\\MicroUI\\MUI_Slider.o

$(OBJDIR_PONG_GAME)\\src\\MicroUI\\MUI_TextBox.o: src\\MicroUI\\MUI_TextBox.c
	$(CC) $(CFLAGS_PONG_GAME) $(INC_PONG_GAME) -c src\\MicroUI\\MUI_TextBox.c -o $(OBJDIR_PONG_GAME)\\src\\MicroUI\\MUI_TextBox.o

$(OBJDIR_PONG_GAME)\\src\\MicroUI\\MicroUI.o: src\\MicroUI\\MicroUI.c
	$(CC) $(CFLAGS_PONG_GAME) $(INC_PONG_GAME) -c src\\MicroUI\\MicroUI.c -o $(OBJDIR_PONG_GAME)\\src\\MicroUI\\MicroUI.o

$(OBJDIR_PONG_GAME)\\src\\Pong.o: src\\Pong.c
	$(CC) $(CFLAGS_PONG_GAME) $(INC_PONG_GAME) -c src\\Pong.c -o $(OBJDIR_PONG_GAME)\\src\\Pong.o

$(OBJDIR_PONG_GAME)\\src\\MicroEngine\\ME_AssetHandler.o: src\\MicroEngine\\ME_AssetHandler.c
	$(CC) $(CFLAGS_PONG_GAME) $(INC_PONG_GAME) -c src\\MicroEngine\\ME_AssetHandler.c -o $(OBJDIR_PONG_GAME)\\src\\MicroEngine\\ME_AssetHandler.o

clean_pong_game: 
	cmd /c del /f $(OBJ_PONG_GAME) $(OUT_PONG_GAME)
	cmd /c rd bin
	cmd /c rd $(OBJDIR_PONG_GAME)\\src\\MicroUI
	cmd /c rd $(OBJDIR_PONG_GAME)\\src\\MicroEngine
	cmd /c rd $(OBJDIR_PONG_GAME)\\src\\MicroPhysics
	cmd /c rd $(OBJDIR_PONG_GAME)\\src

before_microui_test: 
	cmd /c if not exist bin md bin
	cmd /c if not exist $(OBJDIR_MICROUI_TEST)\\src\\MicroUI md $(OBJDIR_MICROUI_TEST)\\src\\MicroUI
	cmd /c if not exist $(OBJDIR_MICROUI_TEST)\\src\\MicroEngine md $(OBJDIR_MICROUI_TEST)\\src\\MicroEngine
	cmd /c if not exist $(OBJDIR_MICROUI_TEST)\\src\\MicroPhysics md $(OBJDIR_MICROUI_TEST)\\src\\MicroPhysics
	cmd /c if not exist $(OBJDIR_MICROUI_TEST)\\src md $(OBJDIR_MICROUI_TEST)\\src

after_microui_test: 

microui_test: before_microui_test out_microui_test after_microui_test

out_microui_test: before_microui_test $(OBJ_MICROUI_TEST) $(DEP_MICROUI_TEST)
	$(LD) $(LIBDIR_MICROUI_TEST) -o $(OUT_MICROUI_TEST) $(OBJ_MICROUI_TEST)  $(LDFLAGS_MICROUI_TEST) $(LIB_MICROUI_TEST)

$(OBJDIR_MICROUI_TEST)\\src\\MicroUI\\MUI_Button.o: src\\MicroUI\\MUI_Button.c
	$(CC) $(CFLAGS_MICROUI_TEST) $(INC_MICROUI_TEST) -c src\\MicroUI\\MUI_Button.c -o $(OBJDIR_MICROUI_TEST)\\src\\MicroUI\\MUI_Button.o

$(OBJDIR_MICROUI_TEST)\\src\\MicroEngine\\ME_GameObject.o: src\\MicroEngine\\ME_GameObject.c
	$(CC) $(CFLAGS_MICROUI_TEST) $(INC_MICROUI_TEST) -c src\\MicroEngine\\ME_GameObject.c -o $(OBJDIR_MICROUI_TEST)\\src\\MicroEngine\\ME_GameObject.o

$(OBJDIR_MICROUI_TEST)\\src\\MicroEngine\\ME_ParticleSystem.o: src\\MicroEngine\\ME_ParticleSystem.c
	$(CC) $(CFLAGS_MICROUI_TEST) $(INC_MICROUI_TEST) -c src\\MicroEngine\\ME_ParticleSystem.c -o $(OBJDIR_MICROUI_TEST)\\src\\MicroEngine\\ME_ParticleSystem.o

$(OBJDIR_MICROUI_TEST)\\src\\MicroEngine\\ME_Renderer.o: src\\MicroEngine\\ME_Renderer.c
	$(CC) $(CFLAGS_MICROUI_TEST) $(INC_MICROUI_TEST) -c src\\MicroEngine\\ME_Renderer.c -o $(OBJDIR_MICROUI_TEST)\\src\\MicroEngine\\ME_Renderer.o

$(OBJDIR_MICROUI_TEST)\\src\\MicroEngine\\ME_Utility.o: src\\MicroEngine\\ME_Utility.c
	$(CC) $(CFLAGS_MICROUI_TEST) $(INC_MICROUI_TEST) -c src\\MicroEngine\\ME_Utility.c -o $(OBJDIR_MICROUI_TEST)\\src\\MicroEngine\\ME_Utility.o

$(OBJDIR_MICROUI_TEST)\\src\\MicroEngine\\ME_Vector2D.o: src\\MicroEngine\\ME_Vector2D.c
	$(CC) $(CFLAGS_MICROUI_TEST) $(INC_MICROUI_TEST) -c src\\MicroEngine\\ME_Vector2D.c -o $(OBJDIR_MICROUI_TEST)\\src\\MicroEngine\\ME_Vector2D.o

$(OBJDIR_MICROUI_TEST)\\src\\MicroEngine\\MicroEngine.o: src\\MicroEngine\\MicroEngine.c
	$(CC) $(CFLAGS_MICROUI_TEST) $(INC_MICROUI_TEST) -c src\\MicroEngine\\MicroEngine.c -o $(OBJDIR_MICROUI_TEST)\\src\\MicroEngine\\MicroEngine.o

$(OBJDIR_MICROUI_TEST)\\src\\MicroPhysics\\MicroPhysics.o: src\\MicroPhysics\\MicroPhysics.c
	$(CC) $(CFLAGS_MICROUI_TEST) $(INC_MICROUI_TEST) -c src\\MicroPhysics\\MicroPhysics.c -o $(OBJDIR_MICROUI_TEST)\\src\\MicroPhysics\\MicroPhysics.o

$(OBJDIR_MICROUI_TEST)\\src\\MicroEngine\\ME_Camer2D.o: src\\MicroEngine\\ME_Camer2D.c
	$(CC) $(CFLAGS_MICROUI_TEST) $(INC_MICROUI_TEST) -c src\\MicroEngine\\ME_Camer2D.c -o $(OBJDIR_MICROUI_TEST)\\src\\MicroEngine\\ME_Camer2D.o

$(OBJDIR_MICROUI_TEST)\\src\\MicroUI\\MUI_CheckBox.o: src\\MicroUI\\MUI_CheckBox.c
	$(CC) $(CFLAGS_MICROUI_TEST) $(INC_MICROUI_TEST) -c src\\MicroUI\\MUI_CheckBox.c -o $(OBJDIR_MICROUI_TEST)\\src\\MicroUI\\MUI_CheckBox.o

$(OBJDIR_MICROUI_TEST)\\src\\MicroUI\\MUI_Slider.o: src\\MicroUI\\MUI_Slider.c
	$(CC) $(CFLAGS_MICROUI_TEST) $(INC_MICROUI_TEST) -c src\\MicroUI\\MUI_Slider.c -o $(OBJDIR_MICROUI_TEST)\\src\\MicroUI\\MUI_Slider.o

$(OBJDIR_MICROUI_TEST)\\src\\MicroUI\\MUI_TextBox.o: src\\MicroUI\\MUI_TextBox.c
	$(CC) $(CFLAGS_MICROUI_TEST) $(INC_MICROUI_TEST) -c src\\MicroUI\\MUI_TextBox.c -o $(OBJDIR_MICROUI_TEST)\\src\\MicroUI\\MUI_TextBox.o

$(OBJDIR_MICROUI_TEST)\\src\\MicroUI\\MicroUI.o: src\\MicroUI\\MicroUI.c
	$(CC) $(CFLAGS_MICROUI_TEST) $(INC_MICROUI_TEST) -c src\\MicroUI\\MicroUI.c -o $(OBJDIR_MICROUI_TEST)\\src\\MicroUI\\MicroUI.o

$(OBJDIR_MICROUI_TEST)\\src\\MicroUI_Test.o: src\\MicroUI_Test.c
	$(CC) $(CFLAGS_MICROUI_TEST) $(INC_MICROUI_TEST) -c src\\MicroUI_Test.c -o $(OBJDIR_MICROUI_TEST)\\src\\MicroUI_Test.o

$(OBJDIR_MICROUI_TEST)\\src\\MicroEngine\\ME_AssetHandler.o: src\\MicroEngine\\ME_AssetHandler.c
	$(CC) $(CFLAGS_MICROUI_TEST) $(INC_MICROUI_TEST) -c src\\MicroEngine\\ME_AssetHandler.c -o $(OBJDIR_MICROUI_TEST)\\src\\MicroEngine\\ME_AssetHandler.o

clean_microui_test: 
	cmd /c del /f $(OBJ_MICROUI_TEST) $(OUT_MICROUI_TEST)
	cmd /c rd bin
	cmd /c rd $(OBJDIR_MICROUI_TEST)\\src\\MicroUI
	cmd /c rd $(OBJDIR_MICROUI_TEST)\\src\\MicroEngine
	cmd /c rd $(OBJDIR_MICROUI_TEST)\\src\\MicroPhysics
	cmd /c rd $(OBJDIR_MICROUI_TEST)\\src

before_spaceship_game: 
	cmd /c if not exist bin md bin
	cmd /c if not exist $(OBJDIR_SPACESHIP_GAME)\\src\\MicroUI md $(OBJDIR_SPACESHIP_GAME)\\src\\MicroUI
	cmd /c if not exist $(OBJDIR_SPACESHIP_GAME)\\src\\MicroEngine md $(OBJDIR_SPACESHIP_GAME)\\src\\MicroEngine
	cmd /c if not exist $(OBJDIR_SPACESHIP_GAME)\\src\\MicroPhysics md $(OBJDIR_SPACESHIP_GAME)\\src\\MicroPhysics
	cmd /c if not exist $(OBJDIR_SPACESHIP_GAME)\\src md $(OBJDIR_SPACESHIP_GAME)\\src

after_spaceship_game: 

spaceship_game: before_spaceship_game out_spaceship_game after_spaceship_game

out_spaceship_game: before_spaceship_game $(OBJ_SPACESHIP_GAME) $(DEP_SPACESHIP_GAME)
	$(LD) $(LIBDIR_SPACESHIP_GAME) -o $(OUT_SPACESHIP_GAME) $(OBJ_SPACESHIP_GAME)  $(LDFLAGS_SPACESHIP_GAME) $(LIB_SPACESHIP_GAME)

$(OBJDIR_SPACESHIP_GAME)\\src\\MicroUI\\MUI_Button.o: src\\MicroUI\\MUI_Button.c
	$(CC) $(CFLAGS_SPACESHIP_GAME) $(INC_SPACESHIP_GAME) -c src\\MicroUI\\MUI_Button.c -o $(OBJDIR_SPACESHIP_GAME)\\src\\MicroUI\\MUI_Button.o

$(OBJDIR_SPACESHIP_GAME)\\src\\MicroEngine\\ME_GameObject.o: src\\MicroEngine\\ME_GameObject.c
	$(CC) $(CFLAGS_SPACESHIP_GAME) $(INC_SPACESHIP_GAME) -c src\\MicroEngine\\ME_GameObject.c -o $(OBJDIR_SPACESHIP_GAME)\\src\\MicroEngine\\ME_GameObject.o

$(OBJDIR_SPACESHIP_GAME)\\src\\MicroEngine\\ME_ParticleSystem.o: src\\MicroEngine\\ME_ParticleSystem.c
	$(CC) $(CFLAGS_SPACESHIP_GAME) $(INC_SPACESHIP_GAME) -c src\\MicroEngine\\ME_ParticleSystem.c -o $(OBJDIR_SPACESHIP_GAME)\\src\\MicroEngine\\ME_ParticleSystem.o

$(OBJDIR_SPACESHIP_GAME)\\src\\MicroEngine\\ME_Renderer.o: src\\MicroEngine\\ME_Renderer.c
	$(CC) $(CFLAGS_SPACESHIP_GAME) $(INC_SPACESHIP_GAME) -c src\\MicroEngine\\ME_Renderer.c -o $(OBJDIR_SPACESHIP_GAME)\\src\\MicroEngine\\ME_Renderer.o

$(OBJDIR_SPACESHIP_GAME)\\src\\MicroEngine\\ME_Utility.o: src\\MicroEngine\\ME_Utility.c
	$(CC) $(CFLAGS_SPACESHIP_GAME) $(INC_SPACESHIP_GAME) -c src\\MicroEngine\\ME_Utility.c -o $(OBJDIR_SPACESHIP_GAME)\\src\\MicroEngine\\ME_Utility.o

$(OBJDIR_SPACESHIP_GAME)\\src\\MicroEngine\\ME_Vector2D.o: src\\MicroEngine\\ME_Vector2D.c
	$(CC) $(CFLAGS_SPACESHIP_GAME) $(INC_SPACESHIP_GAME) -c src\\MicroEngine\\ME_Vector2D.c -o $(OBJDIR_SPACESHIP_GAME)\\src\\MicroEngine\\ME_Vector2D.o

$(OBJDIR_SPACESHIP_GAME)\\src\\MicroEngine\\MicroEngine.o: src\\MicroEngine\\MicroEngine.c
	$(CC) $(CFLAGS_SPACESHIP_GAME) $(INC_SPACESHIP_GAME) -c src\\MicroEngine\\MicroEngine.c -o $(OBJDIR_SPACESHIP_GAME)\\src\\MicroEngine\\MicroEngine.o

$(OBJDIR_SPACESHIP_GAME)\\src\\MicroPhysics\\MicroPhysics.o: src\\MicroPhysics\\MicroPhysics.c
	$(CC) $(CFLAGS_SPACESHIP_GAME) $(INC_SPACESHIP_GAME) -c src\\MicroPhysics\\MicroPhysics.c -o $(OBJDIR_SPACESHIP_GAME)\\src\\MicroPhysics\\MicroPhysics.o

$(OBJDIR_SPACESHIP_GAME)\\src\\MicroEngine\\ME_Camer2D.o: src\\MicroEngine\\ME_Camer2D.c
	$(CC) $(CFLAGS_SPACESHIP_GAME) $(INC_SPACESHIP_GAME) -c src\\MicroEngine\\ME_Camer2D.c -o $(OBJDIR_SPACESHIP_GAME)\\src\\MicroEngine\\ME_Camer2D.o

$(OBJDIR_SPACESHIP_GAME)\\src\\MicroUI\\MUI_CheckBox.o: src\\MicroUI\\MUI_CheckBox.c
	$(CC) $(CFLAGS_SPACESHIP_GAME) $(INC_SPACESHIP_GAME) -c src\\MicroUI\\MUI_CheckBox.c -o $(OBJDIR_SPACESHIP_GAME)\\src\\MicroUI\\MUI_CheckBox.o

$(OBJDIR_SPACESHIP_GAME)\\src\\MicroUI\\MUI_Slider.o: src\\MicroUI\\MUI_Slider.c
	$(CC) $(CFLAGS_SPACESHIP_GAME) $(INC_SPACESHIP_GAME) -c src\\MicroUI\\MUI_Slider.c -o $(OBJDIR_SPACESHIP_GAME)\\src\\MicroUI\\MUI_Slider.o

$(OBJDIR_SPACESHIP_GAME)\\src\\MicroUI\\MUI_TextBox.o: src\\MicroUI\\MUI_TextBox.c
	$(CC) $(CFLAGS_SPACESHIP_GAME) $(INC_SPACESHIP_GAME) -c src\\MicroUI\\MUI_TextBox.c -o $(OBJDIR_SPACESHIP_GAME)\\src\\MicroUI\\MUI_TextBox.o

$(OBJDIR_SPACESHIP_GAME)\\src\\MicroUI\\MicroUI.o: src\\MicroUI\\MicroUI.c
	$(CC) $(CFLAGS_SPACESHIP_GAME) $(INC_SPACESHIP_GAME) -c src\\MicroUI\\MicroUI.c -o $(OBJDIR_SPACESHIP_GAME)\\src\\MicroUI\\MicroUI.o

$(OBJDIR_SPACESHIP_GAME)\\src\\SpaceShip_Game.o: src\\SpaceShip_Game.c
	$(CC) $(CFLAGS_SPACESHIP_GAME) $(INC_SPACESHIP_GAME) -c src\\SpaceShip_Game.c -o $(OBJDIR_SPACESHIP_GAME)\\src\\SpaceShip_Game.o

$(OBJDIR_SPACESHIP_GAME)\\src\\MicroEngine\\ME_AssetHandler.o: src\\MicroEngine\\ME_AssetHandler.c
	$(CC) $(CFLAGS_SPACESHIP_GAME) $(INC_SPACESHIP_GAME) -c src\\MicroEngine\\ME_AssetHandler.c -o $(OBJDIR_SPACESHIP_GAME)\\src\\MicroEngine\\ME_AssetHandler.o

clean_spaceship_game: 
	cmd /c del /f $(OBJ_SPACESHIP_GAME) $(OUT_SPACESHIP_GAME)
	cmd /c rd bin
	cmd /c rd $(OBJDIR_SPACESHIP_GAME)\\src\\MicroUI
	cmd /c rd $(OBJDIR_SPACESHIP_GAME)\\src\\MicroEngine
	cmd /c rd $(OBJDIR_SPACESHIP_GAME)\\src\\MicroPhysics
	cmd /c rd $(OBJDIR_SPACESHIP_GAME)\\src

before_flappybird_clone_game: 
	cmd /c if not exist bin md bin
	cmd /c if not exist $(OBJDIR_FLAPPYBIRD_CLONE_GAME)\\src\\MicroUI md $(OBJDIR_FLAPPYBIRD_CLONE_GAME)\\src\\MicroUI
	cmd /c if not exist $(OBJDIR_FLAPPYBIRD_CLONE_GAME)\\src\\MicroEngine md $(OBJDIR_FLAPPYBIRD_CLONE_GAME)\\src\\MicroEngine
	cmd /c if not exist $(OBJDIR_FLAPPYBIRD_CLONE_GAME)\\src\\MicroPhysics md $(OBJDIR_FLAPPYBIRD_CLONE_GAME)\\src\\MicroPhysics
	cmd /c if not exist $(OBJDIR_FLAPPYBIRD_CLONE_GAME)\\src md $(OBJDIR_FLAPPYBIRD_CLONE_GAME)\\src

after_flappybird_clone_game: 

flappybird_clone_game: before_flappybird_clone_game out_flappybird_clone_game after_flappybird_clone_game

out_flappybird_clone_game: before_flappybird_clone_game $(OBJ_FLAPPYBIRD_CLONE_GAME) $(DEP_FLAPPYBIRD_CLONE_GAME)
	$(LD) $(LIBDIR_FLAPPYBIRD_CLONE_GAME) -o $(OUT_FLAPPYBIRD_CLONE_GAME) $(OBJ_FLAPPYBIRD_CLONE_GAME)  $(LDFLAGS_FLAPPYBIRD_CLONE_GAME) $(LIB_FLAPPYBIRD_CLONE_GAME)

$(OBJDIR_FLAPPYBIRD_CLONE_GAME)\\src\\MicroUI\\MUI_Button.o: src\\MicroUI\\MUI_Button.c
	$(CC) $(CFLAGS_FLAPPYBIRD_CLONE_GAME) $(INC_FLAPPYBIRD_CLONE_GAME) -c src\\MicroUI\\MUI_Button.c -o $(OBJDIR_FLAPPYBIRD_CLONE_GAME)\\src\\MicroUI\\MUI_Button.o

$(OBJDIR_FLAPPYBIRD_CLONE_GAME)\\src\\MicroEngine\\ME_GameObject.o: src\\MicroEngine\\ME_GameObject.c
	$(CC) $(CFLAGS_FLAPPYBIRD_CLONE_GAME) $(INC_FLAPPYBIRD_CLONE_GAME) -c src\\MicroEngine\\ME_GameObject.c -o $(OBJDIR_FLAPPYBIRD_CLONE_GAME)\\src\\MicroEngine\\ME_GameObject.o

$(OBJDIR_FLAPPYBIRD_CLONE_GAME)\\src\\MicroEngine\\ME_ParticleSystem.o: src\\MicroEngine\\ME_ParticleSystem.c
	$(CC) $(CFLAGS_FLAPPYBIRD_CLONE_GAME) $(INC_FLAPPYBIRD_CLONE_GAME) -c src\\MicroEngine\\ME_ParticleSystem.c -o $(OBJDIR_FLAPPYBIRD_CLONE_GAME)\\src\\MicroEngine\\ME_ParticleSystem.o

$(OBJDIR_FLAPPYBIRD_CLONE_GAME)\\src\\MicroEngine\\ME_Renderer.o: src\\MicroEngine\\ME_Renderer.c
	$(CC) $(CFLAGS_FLAPPYBIRD_CLONE_GAME) $(INC_FLAPPYBIRD_CLONE_GAME) -c src\\MicroEngine\\ME_Renderer.c -o $(OBJDIR_FLAPPYBIRD_CLONE_GAME)\\src\\MicroEngine\\ME_Renderer.o

$(OBJDIR_FLAPPYBIRD_CLONE_GAME)\\src\\MicroEngine\\ME_Utility.o: src\\MicroEngine\\ME_Utility.c
	$(CC) $(CFLAGS_FLAPPYBIRD_CLONE_GAME) $(INC_FLAPPYBIRD_CLONE_GAME) -c src\\MicroEngine\\ME_Utility.c -o $(OBJDIR_FLAPPYBIRD_CLONE_GAME)\\src\\MicroEngine\\ME_Utility.o

$(OBJDIR_FLAPPYBIRD_CLONE_GAME)\\src\\MicroEngine\\ME_Vector2D.o: src\\MicroEngine\\ME_Vector2D.c
	$(CC) $(CFLAGS_FLAPPYBIRD_CLONE_GAME) $(INC_FLAPPYBIRD_CLONE_GAME) -c src\\MicroEngine\\ME_Vector2D.c -o $(OBJDIR_FLAPPYBIRD_CLONE_GAME)\\src\\MicroEngine\\ME_Vector2D.o

$(OBJDIR_FLAPPYBIRD_CLONE_GAME)\\src\\MicroEngine\\MicroEngine.o: src\\MicroEngine\\MicroEngine.c
	$(CC) $(CFLAGS_FLAPPYBIRD_CLONE_GAME) $(INC_FLAPPYBIRD_CLONE_GAME) -c src\\MicroEngine\\MicroEngine.c -o $(OBJDIR_FLAPPYBIRD_CLONE_GAME)\\src\\MicroEngine\\MicroEngine.o

$(OBJDIR_FLAPPYBIRD_CLONE_GAME)\\src\\MicroPhysics\\MicroPhysics.o: src\\MicroPhysics\\MicroPhysics.c
	$(CC) $(CFLAGS_FLAPPYBIRD_CLONE_GAME) $(INC_FLAPPYBIRD_CLONE_GAME) -c src\\MicroPhysics\\MicroPhysics.c -o $(OBJDIR_FLAPPYBIRD_CLONE_GAME)\\src\\MicroPhysics\\MicroPhysics.o

$(OBJDIR_FLAPPYBIRD_CLONE_GAME)\\src\\MicroEngine\\ME_Camer2D.o: src\\MicroEngine\\ME_Camer2D.c
	$(CC) $(CFLAGS_FLAPPYBIRD_CLONE_GAME) $(INC_FLAPPYBIRD_CLONE_GAME) -c src\\MicroEngine\\ME_Camer2D.c -o $(OBJDIR_FLAPPYBIRD_CLONE_GAME)\\src\\MicroEngine\\ME_Camer2D.o

$(OBJDIR_FLAPPYBIRD_CLONE_GAME)\\src\\MicroUI\\MUI_CheckBox.o: src\\MicroUI\\MUI_CheckBox.c
	$(CC) $(CFLAGS_FLAPPYBIRD_CLONE_GAME) $(INC_FLAPPYBIRD_CLONE_GAME) -c src\\MicroUI\\MUI_CheckBox.c -o $(OBJDIR_FLAPPYBIRD_CLONE_GAME)\\src\\MicroUI\\MUI_CheckBox.o

$(OBJDIR_FLAPPYBIRD_CLONE_GAME)\\src\\MicroUI\\MUI_Slider.o: src\\MicroUI\\MUI_Slider.c
	$(CC) $(CFLAGS_FLAPPYBIRD_CLONE_GAME) $(INC_FLAPPYBIRD_CLONE_GAME) -c src\\MicroUI\\MUI_Slider.c -o $(OBJDIR_FLAPPYBIRD_CLONE_GAME)\\src\\MicroUI\\MUI_Slider.o

$(OBJDIR_FLAPPYBIRD_CLONE_GAME)\\src\\MicroUI\\MUI_TextBox.o: src\\MicroUI\\MUI_TextBox.c
	$(CC) $(CFLAGS_FLAPPYBIRD_CLONE_GAME) $(INC_FLAPPYBIRD_CLONE_GAME) -c src\\MicroUI\\MUI_TextBox.c -o $(OBJDIR_FLAPPYBIRD_CLONE_GAME)\\src\\MicroUI\\MUI_TextBox.o

$(OBJDIR_FLAPPYBIRD_CLONE_GAME)\\src\\MicroUI\\MicroUI.o: src\\MicroUI\\MicroUI.c
	$(CC) $(CFLAGS_FLAPPYBIRD_CLONE_GAME) $(INC_FLAPPYBIRD_CLONE_GAME) -c src\\MicroUI\\MicroUI.c -o $(OBJDIR_FLAPPYBIRD_CLONE_GAME)\\src\\MicroUI\\MicroUI.o

$(OBJDIR_FLAPPYBIRD_CLONE_GAME)\\src\\FlappyBird_game.o: src\\FlappyBird_game.c
	$(CC) $(CFLAGS_FLAPPYBIRD_CLONE_GAME) $(INC_FLAPPYBIRD_CLONE_GAME) -c src\\FlappyBird_game.c -o $(OBJDIR_FLAPPYBIRD_CLONE_GAME)\\src\\FlappyBird_game.o

$(OBJDIR_FLAPPYBIRD_CLONE_GAME)\\src\\MicroEngine\\ME_AssetHandler.o: src\\MicroEngine\\ME_AssetHandler.c
	$(CC) $(CFLAGS_FLAPPYBIRD_CLONE_GAME) $(INC_FLAPPYBIRD_CLONE_GAME) -c src\\MicroEngine\\ME_AssetHandler.c -o $(OBJDIR_FLAPPYBIRD_CLONE_GAME)\\src\\MicroEngine\\ME_AssetHandler.o

clean_flappybird_clone_game: 
	cmd /c del /f $(OBJ_FLAPPYBIRD_CLONE_GAME) $(OUT_FLAPPYBIRD_CLONE_GAME)
	cmd /c rd bin
	cmd /c rd $(OBJDIR_FLAPPYBIRD_CLONE_GAME)\\src\\MicroUI
	cmd /c rd $(OBJDIR_FLAPPYBIRD_CLONE_GAME)\\src\\MicroEngine
	cmd /c rd $(OBJDIR_FLAPPYBIRD_CLONE_GAME)\\src\\MicroPhysics
	cmd /c rd $(OBJDIR_FLAPPYBIRD_CLONE_GAME)\\src

.PHONY: before_microengine_test after_microengine_test clean_microengine_test before_pong_game after_pong_game clean_pong_game before_microui_test after_microui_test clean_microui_test before_spaceship_game after_spaceship_game clean_spaceship_game before_flappybird_clone_game after_flappybird_clone_game clean_flappybird_clone_game

